definitions:
  models.ClubhouseProfileResponse:
    properties:
      created_at:
        example: "2021-03-15T15:20:18.066663Z"
        type: string
      id:
        example: 604f7b3253883ed1649ed13a
        type: string
      profile:
        properties:
          bio:
            example: |-
              BackEnd Programmer. 선린인터넷고 정보보호과 3학년 재학중입니다.
              꽈뚜룹, 이근 성대모사 잘합니다.

              Python, Node, Go 관심 많습니다.
            type: string
          clubs:
            items:
              properties:
                club_id:
                  example: 12345
                  type: integer
                description:
                  example: this is a strip club
                  type: string
                enable_private:
                  example: true
                  type: boolean
                is_community:
                  example: false
                  type: boolean
                is_follow_allowed:
                  example: true
                  type: boolean
                is_membership_private:
                  example: false
                  type: boolean
                name:
                  example: strip club
                  type: string
                num_followers:
                  example: 100
                  type: integer
                num_members:
                  example: 20
                  type: integer
                num_online:
                  example: 3
                  type: integer
                photo_url:
                  example: https://clubhouseprod.s3.amazonaws.com:443/club_<club_id>_<guid>_thumbnail_250x250
                  type: string
                rules:
                  items:
                    properties:
                      desc:
                        example: description
                        type: string
                      title:
                        example: title
                        type: string
                    type: object
                  type: array
                url:
                  example: https://www.joinclubhouse.com/club/<clubname>
                  type: string
              type: object
            type: array
          displayname:
            type: string
          instagram:
            example: yeon.gyu.kim
            type: string
          invited_by_user_profile:
            properties:
              name:
                example: Go Taegeon
                type: string
              photo_url:
                example: https://clubhouseprod.s3.amazonaws.com/5652354_2c1840a1-02c0-40ee-b98c-f45598712bcd_thumbnail_250x250
                type: string
              user_id:
                example: 5652354
                type: integer
              username:
                example: gtg7784
                type: string
            type: object
          name:
            example: YeonGyu Kim
            type: string
          num_followers:
            example: 84
            type: integer
          num_following:
            example: 163
            type: integer
          photo_url:
            example: https://clubhouseprod.s3.amazonaws.com/711498010_dcbb5803-9985-4ec5-b36a-0ac86284ff92
            type: string
          time_created:
            example: "2021-02-08T15:03:08.132077+00:00"
            type: string
          twitter:
            type: string
          url:
            example: https://www.joinclubhouse.com/@yeon.gyu.kim
            type: string
          username:
            example: yeon.gyu.kim
            type: string
        type: object
      updated_at:
        example: "2021-03-15T15:20:18.066664Z"
        type: string
      user_id:
        example: 711498010
        type: integer
      username:
        example: yeon.gyu.kim
        type: string
    type: object
info:
  contact: {}
paths:
  /profile/:username:
    get:
      consumes:
      - application/json
      description: Retrieve a profile from clubhouse by given username
      parameters:
      - description: Username
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ClubhouseProfileResponse'
        "404":
          description: ""
      summary: Retrieve a profile from clubhouse by given username
swagger: "2.0"
